// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRlKSDzZDyc0g86wuz_xpqFheXLWhlnoc',
    appId: '1:433036287591:web:74aecbf6eb3ce063097ec2',
    messagingSenderId: '433036287591',
    projectId: 'blood-donation-finder-a2b7c',
    authDomain: 'blood-donation-finder-a2b7c.firebaseapp.com',
    storageBucket: 'blood-donation-finder-a2b7c.firebasestorage.app',
    measurementId: 'G-Q6TG1R2Y9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWNTvfBChglKgajeKuXU9Jiu-yomNsesw',
    appId: '1:433036287591:android:d94b926bc2135a59097ec2',
    messagingSenderId: '433036287591',
    projectId: 'blood-donation-finder-a2b7c',
    storageBucket: 'blood-donation-finder-a2b7c.firebasestorage.app',
  );
}